// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PicPay.Data;

#nullable disable

namespace PicPay.Migrations
{
    [DbContext(typeof(PicPayDbContext))]
    [Migration("20241226210410_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PicPay.Model.Entity.TransferEntity", b =>
                {
                    b.Property<Guid>("TranferId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ReceiveId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SerderId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("TranferId");

                    b.HasIndex("ReceiveId");

                    b.HasIndex("SerderId");

                    b.ToTable("Transfer", (string)null);
                });

            modelBuilder.Entity("PicPay.Model.Entity.WalletEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Cash")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email", "Cpf")
                        .IsUnique();

                    b.ToTable("Wallet", (string)null);
                });

            modelBuilder.Entity("PicPay.Model.Entity.TransferEntity", b =>
                {
                    b.HasOne("PicPay.Model.Entity.WalletEntity", "Receive")
                        .WithMany()
                        .HasForeignKey("ReceiveId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Transfer_Receive");

                    b.HasOne("PicPay.Model.Entity.WalletEntity", "Sender")
                        .WithMany()
                        .HasForeignKey("SerderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Transfer_Sender");

                    b.Navigation("Receive");

                    b.Navigation("Sender");
                });
#pragma warning restore 612, 618
        }
    }
}
